name: Auto Labeler

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install @google/generative-ai

      - name: Auto Label
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.issue?.number || context.payload.pull_request?.number;
            const { owner, repo } = context.repo;
            const eventPayload = context.payload.issue || context.payload.pull_request;
            const title = eventPayload.title;
            const body = eventPayload.body;

            if (!issue_number) {
              console.log("Could not get issue or pull request number");
              return;
            }

            const prompt = `Based on the following title and body of an issue or pull request, please provide a comma-separated list of relevant labels.

            Title: ${title}
            Body: ${body}

            Labels:`;

            const { GoogleGenerativeAI } = require("@google/generative-ai");
            const genAI = new GoogleGenerativeAI("${{ secrets.GEMINI_API_KEY }}");
            const model = genAI.getGenerativeModel({ model: "gemini-pro" });

            const result = await model.generateContent(prompt);
            const response = await result.response;
            const text = await response.text();

            const labels = text.split(',').map(label => label.trim()).filter(label => label);

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels,
              });
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}